#!/bin/bash

TODO_FILE="$HOME/todo.md"

if [ "$1" == "-f" ] || [ "$1" == "--file" ]; then
	if [ -z "$2" ]; then
		exit 1
	fi
	TODO_FILE="$2"
	shift 2
fi

case "$1" in
	-e|--edit)
		shift
		${EDITOR:-vi} $TODO_FILE
		;;
	-a|--add)
		shift
		echo "$*" >> "$TODO_FILE"
		;;
esac

if [ -n "$(which bat)" ]; then
	bat $TODO_FILE --paging=never --color=always
elif [ -n "$(which batcat)" ]; then
	batcat $TODO_FILE --paging=never --color=always
else
	echo "please install bat" >&2
	cat $TODO_FILE
fi
