#!/bin/bash

TODO_FILE="$HOME/todo.md"

case "$1" in
	-e|--edit)
		shift
		${EDITOR:-vi} $TODO_FILE
		exit 0
		;;
	-a|--add)
		shift
		echo "$*" >> "$TODO_FILE"
		exit 0
		;;
esac

if [ -n "$(which bat)" ]; then
	bat $TODO_FILE --paging=never --color=always
else
	echo "please install bat" >&2
	cat $TODO_FILE
fi
